---
# 2. Pull container and run it

- name: Pull a Docker image
  docker_image:
    name: sergkudinov/ece-userapi:latest
    source: pull

- name: Start a container
  docker_container:
    name: ece-userapi-1
    image: sergkudinov/ece-userapi:latest
    state: started
    ports:
     - "8080:3000"
